### ISSUE TITLE
Why the pictures of FEATURE MAP looks the same?

### ISSUE THREAD

**Issue by duchengyao** [Nikasa1889/HistoryObjectRecognition#2]

**Comment by Nikasa1889** [comment]
It is because I want to emphasize the fact that we are using the same feature detector to build a feature map. These small (the same) pictures represent the feature that we are looking for on that particular feature map. As you can see in the text next to it, I explain that a feature map is created by applying the same "feature detector" or "filter" at different locations of an input map.

**Comment by Nikasa1889** [comment]
Solved

**Comment by duchengyao** [comment]
Thanks so much!
